### ISSUE TITLE
cat: /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin: No such file or directory

### ISSUE THREAD

**Issue by farukca** [kaspergrubbe/simple-capistrano-unicorn#4]
"cap production deploy" doing all staff and while restarting unicorn, it gets error. Error messages are;

```
SSHKit::Runner::ExecuteError: Exception while executing as user@xx.xxx.xxx.xx: cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin exit status: 1
cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin stdout: Nothing written
cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin stderr: cat: /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin: No such file or directory

SSHKit::Command::Failed: cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin exit status: 1
cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin stdout: Nothing written
cat /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin stderr: cat: /var/www/testapp/shared/tmp/pids/unicorn.pid.oldbin: No such file or directory
```

I have created a file with name; "unicorn.pid.oldbin" and put same pid value from unicorn.pid. But after deploy command, it is deleting this oldbin file and giving same error again.

Thanks, best regards.

**Comment by kaspergrubbe** [comment]
Hi @farukca 

Could you include your config files `unicorn.rb`, `config/deploy.rb` and your relevant `config/deploy/*.rb` file?

Also, which version of this gem are you using?

**Comment by kaspergrubbe** [comment]
What should happen when you do a deploy/restart is defined like this:

## 1. Make sure that all servers are running a Unicorn master, if not, start one.

## 2. Send the `USR2` signal to all running current Unicorn masters to let them reload code and start a new master

Sending the USR2 signal tells a current Unicorn master to spawn a new Master, but not switch the traffic over yet.

## 3. Send the `WINCH` signal to current Unicorn master so the new Unicorn Master can take over.

The new Unicorn Master is now handling all the traffic. This is where the `.oldbin` file gets written.

## 4. Send the `QUIT` signal to old Unicorn master

We haven't killed the old master yet (in old releases I allowed for you to rollback to the old master if there was any issues).

But now we send the `QUIT` signal.

## Process 

This process is described by the Unicorn process right here (scroll down to "Procedure to replace a running unicorn executable"): https://bogomips.org/unicorn/SIGNALS.html

## Likely cause:

Earlier releases of this gem allowed for the new Unicorn Master to kill the old Unicorn Master. This will look something like this in your `unicorn.rb`:

```ruby
# Kill off the new master after forking
old_pid = "#{app_dir}/shared/pids/unicorn.pid.oldbin"
if File.exists?(old_pid) && server.pid != old_pid
  begin
    Process.kill("QUIT", File.read(old_pid).to_i)
  rescue Errno::ENOENT, Errno::ESRCH
    # someone else did our job for us
  end
end
```

This means that your new Unicorn Master likely already did the job for us.

## What you can try to do:

Remove the above mentioned line from your `unicorn.rb`, and let this gem handle it for you. 

Please let me know if it works.

**Comment by farukca** [comment]
Hi,
Sorry for late response; I could not try this earlier.

I have commented  code block in unicorn.rb as you mention; my unicorn.rb and deploy.rb codes are at this gist;    https://gist.github.com/farukca/99da4d2bb47c3ed067a82b6ae39c5f08

But it is still getting same error. As you can see at the gist linked below; it is running unicorn upgrade; and then it is sending USR2 signal and reloading the code. When it tries to kill workers started from old master with WINCH signal;  Running cat /var/www/myapp/shared/tmp/pids/unicorn.pid.oldbin and at this point getting the error; "No such file or directory"

cap deploy log is at this gist;  https://gist.github.com/farukca/b77d9508045551b1adc380c9b54c16b5

Thanks, best regards.

Note: I have also added unicorn service file to this gist which is located under /etc/init.d/unicorn_myapp;   https://gist.github.com/farukca/ee7c7c7d8dabed109cb27600b2bf23ea
Hope it helps,

**Comment by farukca** [comment]
Solved problem, the problem was in init script which is located under /etc/init.d/unicorn_myapp;
I have changed upgrade script to;

`if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
  then
    n=$TIMEOUT
    while test -s $OLD_PIN && test $n -ge 0
    do
      printf '.' && sleep 1 && n=$(( $n - 1 ))
    done
    echo
    if test $n -lt 0 && test -s $OLD_PIN
    then
      echo >&2 "$OLD_PIN still exists after $TIMEOUT seconds"
      exit 1
    fi
    exit 0`

I think, main problem was; previous upgrade script was deleting .oldbin file; and this gem couldn't find .oldbin file.

Thanks, best regards.

**Comment by kaspergrubbe** [comment]
I am glad that you got it working.
